### PR TITLE
0.6.0

### LINKED ISSUE #253: IFC export of Envelope by Sketch fails.
For the Simple Tower workflow, export to IFC succeeds when the Envelope is disabled, but fails when it is enabled.
image

IFC export of Envelope by Sketch fails with the following error:
```
START RequestId: 13ef39b8-e2b7-48dc-b5c5-509d19d444c5 Version: $LATEST
Input: hypar-executions
Output: aacc5fc7-1267-4331-a96f-858f9b7e7e78_elements.zip aacc5fc7-1267-4331-a96f-858f9b7e7e78_model.zip aacc5fc7-1267-4331-a96f-858f9b7e7e78_ifc.zip
Schemas: https://raw.githubusercontent.com/hypar-io/Schemas/master/Origin.json,https://raw.githubusercontent.com/hypar-io/Schemas/master/ContextBuildings.json,https://raw.githubusercontent.com/hypar-io/Schemas/master/Envelope.json,https://raw.githubusercontent.com/hypar-io/Schemas/master/Level.json,https://raw.githubusercontent.com/hypar-io/Schemas/master/FacadePanel.json,https://raw.githubusercontent.com/hypar-io/Schemas/master/LevelPerimeter.json
Generating in-memory assembly for user defined types...
Attempting to download 6115f6a6-08b7-44e2-b7ed-346ee3b0cdc3_a41f8203-530e-4292-8a8d-5016a7c78c54_elements.zip from hypar-executions.
Attempting to download 163c4e96-affe-4366-a9eb-f7483626ed6c_0c8d0526-9490-4d53-896b-88a1515de583_elements.zip from hypar-executions.
Attempting to download f15a3535-c0d3-4600-940a-965334e13d73_e578bbcb-c654-438d-be3a-a81cbeb1784f_elements.zip from hypar-executions.
Attempting to download e6e3c470-373f-44c2-aa44-cd3d815ecdf3_aa0b94eb-6a0d-4f17-b0eb-322bce98bb2a_elements.zip from hypar-executions.
Attempting to download a8a66e73-8f70-4d8e-bfcd-014b73be97cf_c3bb78fd-7dee-41cc-ae2e-f1b4b4ae2794_elements.zip from hypar-executions.
Attempting to download 4c6fa706-f01e-4fd0-a098-56ca942686c0_530886d2-1c18-4a6d-ad21-da4a0db0f37e_elements.zip from hypar-executions.
Creating directory /tmp/b5ea4d9b-c30e-4857-a3e1-be6291a5cb05.
Deleting directory /tmp/b5ea4d9b-c30e-4857-a3e1-be6291a5cb05.
Creating directory /tmp/05f3a8a7-e233-4725-9afe-86d173b800fc.
The following errors occured during model deserialization:
Required property 'Transform' not found in JSON. Path '', line 1, position 19049.
Deleting directory /tmp/05f3a8a7-e233-4725-9afe-86d173b800fc.
Creating directory /tmp/20107e21-2d75-4ac4-94b1-2b9d0281776c.
The following errors occured during model deserialization:
Required property 'Transform' not found in JSON. Path '', line 1, position 35216.
Deleting directory /tmp/20107e21-2d75-4ac4-94b1-2b9d0281776c.
Creating directory /tmp/1ccb0a2a-a2e4-4e79-832e-c2cfc7308048.
Creating directory /tmp/25aa1038-1b7c-4b6b-b9a9-6336ea891f36.
Creating directory /tmp/e016e15c-dbf9-48c1-a933-f1bc3dc195e1.
Deleting directory /tmp/1ccb0a2a-a2e4-4e79-832e-c2cfc7308048.
Deleting directory /tmp/e016e15c-dbf9-48c1-a933-f1bc3dc195e1.
Deleting directory /tmp/25aa1038-1b7c-4b6b-b9a9-6336ea891f36.
Merging models...
Writing glb archive to /tmp/aacc5fc7-1267-4331-a96f-858f9b7e7e78_model.zip.
Uploading glb archive to to hypar-executions/aacc5fc7-1267-4331-a96f-858f9b7e7e78_model.zip.
Deleting file /tmp/aacc5fc7-1267-4331-a96f-858f9b7e7e78_model.zip.
Writing model archive to /tmp/aacc5fc7-1267-4331-a96f-858f9b7e7e78_elements.zip.
Uploading model archive to to hypar-executions/aacc5fc7-1267-4331-a96f-858f9b7e7e78_elements.zip.
Creating ifc file at /tmp/tmpgto8rl.tmp.
Deleting file /tmp/aacc5fc7-1267-4331-a96f-858f9b7e7e78_elements.zip.
One or more errors occurred. (An item with the same key has already been added. Key: envelope): AggregateException
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Elements.Serialization.IFC.IFCModelExtensions.ToIFC(Model model, String path)
   at Hypar.Functions.Execution.AWS.S3ModelStore`1.UploadIfcModelZipAsync(String ifcKey, String bucketName, Model model)
   at Hypar.Functions.Execution.AWS.S3ModelStore`1.SetModelAsync(T args, Model state)
   at ExportServer.AWSHandler.Handler(ExportServerInput input, ILambdaContext context) in /Users/ikeough/Documents/Hypar/ExportServer/src/AWSHandler.cs:line 41

END RequestId: 13ef39b8-e2b7-48dc-b5c5-509d19d444c5
REPORT RequestId: 13ef39b8-e2b7-48dc-b5c5-509d19d444c5	Duration: 13175.87 ms	Billed Duration: 13200 ms	Memory Size: 3008 MB	Max Memory Used: 722 MB
```

### PR DESCRIPTION
**Pull request by ikeough**
BACKGROUND:
Principally, this PR adds the fix for #253. Other additions, including the `Ray` intersection work by @andrewheumann are added here as well as the `AnalysisMesh` work by @ikeough.

DESCRIPTION:
This PR does the following:
- Adds the `AnalysisMesh` and `ColorScale` classes.
- Adds new intersect methods for `Ray`.
- Consolidates all example tests for documentation under their primary test classes and uses the `Trait` attribute to mark them as examples.
- Fixes #253.

### CODE REVIEW

File: src/Elements/Serialization/IFC/IFCModelExtensions.cs [hunk 1]
```diff
@@ -146,7 +147,6 @@ internal static void ToIFC(Model model, string path)
             // IfcRelAssociatesMaterial
             // IfcMaterialDefinitionRepresentation
             // https://forums.buildingsmart.org/t/where-and-how-will-my-colors-be-saved-in-ifc/1806/12
-            var materials = new Dictionary<string, IfcMaterial>();
```
Comment (ikeough) [inline src/Elements/Serialization/IFC/IFCModelExtensions.cs]: This is the fix for #253. This dictionary is not required. Removing it fixes the error where adding two materials of the same name would cause a duplicate key exception.

File: src/Elements/Serialization/glTF/GltfExtensions.cs [hunk 2]
```diff
@@ -676,11 +676,14 @@ private static Gltf InitializeGlTF(Model model, List<byte> buffer, bool drawEdge
...
             materialsToAdd.Add(BuiltInMaterials.Edges);
+            materialsToAdd.Add(BuiltInMaterials.Default);
             var materials = gltf.AddMaterials(materialsToAdd, buffer, bufferViews);
 
             var elements = model.Elements.Where(e =>
             {
-                return e.Value is GeometricElement || e.Value is ElementInstance;
+                return e.Value is GeometricElement || 
+                e.Value is ElementInstance ||
+                e.Value is ITessellate;
```
Comment (mattc) [inline src/Elements/Serialization/glTF/GltfExtensions.cs]: Will there be any ITessellates that aren't also GeometricElements?

File: src/Elements/Geometry/Color.cs [hunk 3]
```diff
@@ -54,5 +54,46 @@ public override string ToString()
...
+        }
+
+        /// <summary>
+        /// Add two colors.
+        /// </summary>
+        /// <param name="a">The first color.</param>
+        /// <param name="b">The second color.</param>
+        public static Color operator +(Color a, Color b)
+        {
+            return new Color(a.Red + b.Red, a.Green + b.Green, a.Blue + b.Blue, a.Alpha + b.Alpha);
```
Comment (mattc) [inline src/Elements/Geometry/Color.cs]: I don't see anything that would keep these values in-range (same with previous functions).

File: src/Elements/Geometry/Color.cs [hunk 4]
```diff
@@ -54,5 +54,46 @@ public override string ToString()
         {
             return $"R:{Red:0.00}, G:{Green:0.00}, B:{Blue:0.00}, A: {Alpha:0.00}";
         }
+
+        /// <summary>
+        /// Linearly interpolate between this color and the provide color.
```
Comment (mattc) [inline src/Elements/Geometry/Color.cs]: `provide` => `provided`. But since the word `other` is used, perhaps it should be that.

File: src/Elements/Serialization/IFC/IFCModelExtensions.cs [hunk 5]
```diff
@@ -157,7 +157,6 @@ internal static void ToIFC(Model model, string path)
             foreach (var m in model.AllElementsOfType<Material>())
             {
                 var material = new IfcMaterial(m.Name, null, "Hypar");
-                materials.Add(m.Name, material);
                 ifc.AddEntity(material);
```
Comment (mattc) [inline src/Elements/Serialization/IFC/IFCModelExtensions.cs]: Will it cause any downstream issues to have two (possibly different) IFC materials with the same name?

File: src/Elements/Serialization/glTF/GltfExtensions.cs (hunk 2 above)
Comment (ikeough) [reply src/Elements/Serialization/glTF/GltfExtensions.cs]: This is a good catch. This was added before we made `AnalysisMesh` a `GeometricElement`. So the short answer to this question is no.

File: src/Elements/Serialization/IFC/IFCModelExtensions.cs (hunk 5 above)
Comment (ikeough) [reply src/Elements/Serialization/IFC/IFCModelExtensions.cs]: I think it comes down to how the application that consumes the IFC treats materials with the same name. There is nothing in the IFC spec that prevents this as `label`, the equivalent IFC field is optional.

File: src/Elements/Geometry/Color.cs (hunk 3 above)
Comment (ikeough) [reply src/Elements/Geometry/Color.cs]: Added a `Math.Max` for `*` and `+` and an `ArgumentException` when the scalar value multiplied by a color is less than 1.0.
