### PR TITLE
winding-based polygon contains, support for holes + xforms for ray intersection

### LINKED ISSUE #257: Ray/Solid intersections do not respect an element's transform or holes.
**Describe the bug**
When intersecting a `Ray` with a `Solid`, the resulting intersections do not respect the transform of the solid's element, and the rays do not traverse through holes in the solid.

**This issue requires the changes in #258 to test.**

**To Reproduce**
1. Run `RayTests.RayShadowTest()`

**Expected behavior**
Rays that intersect solids in elements with transforms will respect the transform. Rays that go through holes in a solid will not cause an intersection.

**Screenshots**
Rays properly intersect a solid in an element without a transform, with the exception of holes where the rays intersect on the face containing the hole.
image
Rays do not properly intersect a solid in an element with a transform.
image

**The Problem with Holes**
The `Ray.Intersects(Face face,...)` API currently uses transform manipulation and clipper operations to test test whether a point is inside a polygon. This involves hundreds of multiplication operations per face. There is an easier and much faster way: http://geomalgorithms.com/a03-_inclusion.html.

### PR DESCRIPTION
**Pull request by andrewheumann**
BACKGROUND:
- Fixes #257 
- Attempts and fails to improve raycasting performance by implementing a Winding Number based polygon contains method. 

DESCRIPTION:
- Adds a `Ray.Intersects(GeometricElement)` method that accounts for the element's transform
- Adds a `Profile.Contains` method that can do region inclusion taking into account holes/voids
- Changes `Ray` to a Struct
- Updates `Ray.Intersects(Face)` to use the new hole-aware containment method
- Adds `Ray.Intersects(Line)`

TESTING:
- Run the updated `RayTests.RayShadowTest`
- Run the `VectorTests.ProfileContains` test (tests 100 points against a complex profile and ensures their inclusion results match those in Rhino / GH).
  
FUTURE WORK:
- The performance of the `Ray.Intersects()` operations could likely still be improved. 
- The code for the winding number stuff introduces a bunch of methods for that purpose only to the Line and Polygon classes. It might be worth consolidating them somehow to avoid cluttering up the classes with single-purpose methods.
- The test for ProfileContains could probably be less obscure.

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/elements/273)

### CODE REVIEW

File: src/Elements/Geometry/Ray.cs [hunk 1]
```diff
@@ -80,6 +80,35 @@ public bool Intersects(Triangle tri, out Vector3 result)
...
+        public bool Intersects(GeometricElement element, out List<Vector3> result)
+        {
+            List<Vector3> resultsOut = new List<Vector3>();
+            var transformFromElement = new Transform(element.Transform);
+            transformFromElement.Invert();
+            var transformToElement = new Transform(element.Transform);
+            var transformMinusTranslation = new Transform(transformFromElement);
+            transformMinusTranslation.Move(-1 * transformMinusTranslation.Origin); // 
+            var transformedRay = new Ray(transformFromElement.OfPoint(Origin), transformMinusTranslation.OfVector(Direction));
+            //TODO: handle voids
```
Comment (ikeough) [inline src/Elements/Geometry/Ray.cs]: Is this still `TODO`?

File: src/Elements/Geometry/Line.cs [hunk 2]
```diff
@@ -435,5 +435,45 @@ internal override IList<Vector3> RenderVertices()
...
+            return Start.X <= location.X;
+        }
+
+        internal bool LocationInRange(Vector3 location, Orientation orientation)
+        {
+            if (orientation == Orientation.Ascending) return End.X > location.X;
+
+            return End.X <= location.X;
+        }
+        internal enum Position
```
Comment (ikeough) [inline src/Elements/Geometry/Line.cs]: whitespace

File: src/Elements/Geometry/Line.cs [hunk 3]
```diff
@@ -435,5 +435,45 @@ internal override IList<Vector3> RenderVertices()
...
         }
+
+        #region WindingNumberCalcs
+        internal Position RelativePositionOf(Vector3 location)
+        {
+            double positionCalculation =
+                (End.Y - Start.Y) * (location.X - Start.X) -
+                (location.Y - Start.Y) * (End.X - Start.X);
+
+            if (positionCalculation > 0) { return Position.Left; }
```
Comment (ikeough) [inline src/Elements/Geometry/Line.cs]: Put all blocks on separate row:
```
if (positionCalculation > 0)
{
...
}
```

File: src/Elements/Geometry/Line.cs [hunk 4]
```diff
@@ -435,5 +435,45 @@ internal override IList<Vector3> RenderVertices()
...
+        }
+
+        internal bool AscendingRelativeTo(Vector3 location)
+        {
+            return Start.X <= location.X;
+        }
+
+        internal bool LocationInRange(Vector3 location, Orientation orientation)
+        {
+            if (orientation == Orientation.Ascending) return End.X > location.X;
```
Comment (ikeough) [inline src/Elements/Geometry/Line.cs]: Always use brackets. See message above about blocks.

File: src/Elements/Geometry/Polygon.cs [hunk 5]
```diff
@@ -56,6 +56,55 @@ public bool Contains(Vector3 vector)
...
+        // Adapted from https://stackoverflow.com/questions/46144205/point-in-polygon-using-winding-number/46144206
+        internal static bool Contains2D(IEnumerable<Line> segments, Vector3 location)
+        {
+            int windingNumber = 0;
+
+            foreach (var edge in segments)
+            {
+                // check for coincidence with edge vertices
+                var toStart = location - edge.Start;
+                if (toStart.IsZero()) return true;
```
Comment (ikeough) [inline src/Elements/Geometry/Polygon.cs]: See message above about brackets.

File: src/Elements/Geometry/Profile.cs [hunk 6]
```diff
@@ -185,5 +185,21 @@ public bool Equals(Profile other)
             }
             return this.Perimeter.Equals(other.Perimeter);
         }
+
+        /// <summary>
+        /// Tests if a point is contained within this profile. Returns false for points that are outside of the profile (or within voids). 
+        /// </summary>
+        /// <param name="point">The position to test.</param>
+        /// <returns>True if the point is within the profile.</returns>
+        public bool Contains2D(Vector3 point)
```
Comment (ikeough) [inline src/Elements/Geometry/Profile.cs]: The name of this method is suspect. What would `Contains3D` do?

File: src/Elements/Geometry/Ray.cs (hunk 1 above)
Comment (andrewheumann) [reply src/Elements/Geometry/Ray.cs]: Yes — it is contingent on support for void Solids in elements in the first place!

**Comment by andrewheumann** [comment]
These changes additionally:
- Define a new Containment enum to represent the status of a point within a region or volume (inside, outside, at vertex, at edge, or at face)
- pass out a containment value from all Contains functions
- Define a new constructor for Profile that can take an unordered set of Polygons and figure out which one is "outside".

File: src/Elements/Geometry/Containment.cs [hunk 7]
```diff
@@ -0,0 +1,30 @@
+﻿using System;
+namespace Elements.Geometry
+{
+    /// <summary>
+    /// Represents the state of containment of a point relative to an enclosing polygon, profile, or volume
```
Comment (ikeough) [inline src/Elements/Geometry/Containment.cs]: `The containment of a point relative to an enclosing polygon, profile, or solid.`

File: src/Elements/Geometry/Ray.cs [hunk 8]
```diff
@@ -128,12 +158,14 @@ internal bool Intersects(Face face, out Vector3 result)
...
             {
                 var boundaryPolygon = face.Outer.ToPolygon();
+                var voids = face.Inner?.Select(v => v.ToPolygon())?.ToList();
                 var transformToPolygon = new Transform(plane.Origin, plane.Normal);
                 var transformFromPolygon = new Transform(transformToPolygon);
                 transformFromPolygon.Invert();
-                var transformedPolygon = transformFromPolygon.OfPolygon(boundaryPolygon);
                 var transformedIntersection = transformFromPolygon.OfVector(intersection);
-                if (transformedPolygon.Contains(transformedIntersection) || transformedPolygon.Touches(transformedIntersection))
+                var profile = new Profile(boundaryPolygon, voids, default, "");
```
[the remark this answers is not in the document]
Comment (ikeough) [reply src/Elements/Geometry/Ray.cs]: I see that we're doing this to use some of the new methods that were created. I'll allow it. I wonder if the ray crossing method is faster for these situations.

File: src/Elements/Geometry/Ray.cs [hunk 9]
```diff
@@ -80,6 +80,35 @@ public bool Intersects(Triangle tri, out Vector3 result)
...
+        /// <param name="result">The list of intersection results.</param>
+        /// <returns></returns>
+        public bool Intersects(GeometricElement element, out List<Vector3> result)
+        {
+            List<Vector3> resultsOut = new List<Vector3>();
+            var transformFromElement = new Transform(element.Transform);
+            transformFromElement.Invert();
+            var transformToElement = new Transform(element.Transform);
+            var transformMinusTranslation = new Transform(transformFromElement);
+            transformMinusTranslation.Move(-1 * transformMinusTranslation.Origin); //
```
Comment (ikeough) [inline src/Elements/Geometry/Ray.cs]: Is `Origin.Negate()` better here?

File: test/Elements.Tests/VectorTests.cs [hunk 10]
```diff
@@ -84,34 +85,206 @@ public void DistanceToPlane()
...
+                {
+                    new Vector3(-3.28355342951497,-2.6460367928868,0),
+                    new Vector3(-2.87188183213404,-2.34663926751885,0),
+                    new Vector3(-3.20092267684535,-1.8942081060408,0),
+                    new Vector3(-3.61259427422628,-2.19360563140875,0)
+                })
+            };
+
+            var profile = new Profile(perimeter, voids, default, "");
+            var ptsToTest = new Dictionary<Vector3, bool>
```
Comment (ikeough) [inline test/Elements.Tests/VectorTests.cs]: This seems like a really specific dictionary of points. Do we want to put these in a JSON and read them in? What are they?

Comment (andrewheumann) [reply test/Elements.Tests/VectorTests.cs]: It's just a test of a crazy polygon I drew in rhino along with a hundred random samples and their results. Just making sure our containment results agree with theirs. But I can see how this is overkill.

File: src/Elements/Geometry/Ray.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (andrewheumann) [reply src/Elements/Geometry/Ray.cs]: This is a good point. I'm switching to using the internal method that profile.contains uses, which just tests a collection of segments.
